server:
  error:
    include-message: always
    include-binding-errors: always
confirmation:
  token:
    validity:
      period:
        minutes: 15
default:
  user:
    name: admin
    password: admin
spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  datasource:
    password: '!Password1'
    url: jdbc:mysql://localhost:3306/online-store
    username: root
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL55Dialect
        format_sql: true
    show-sql: true
    open-in-view: false

  mail:
    host: localhost
    port: 1025
    username: hello
    password: hello

    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000
